### ISSUE TITLE
Potential issue in Objects/typeobject.c: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [siva-msft/cpython#2]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

**2 instances** of this defect were found in the following locations:

---
**Instance 1**
File : `Objects/typeobject.c` 
Enclosing Function : `type_set_bases`
Function : `PyArg_UnpackTuple` 
https://github.com/siva-msft/cpython/blob/582aaf19e8b94a70c1f96792197770d604ba0fdf/Objects/typeobject.c#L825
**Issue in**: _cls_

**Code extract**:

```cpp
        PyTypeObject *cls;
        PyObject *new_mro, *old_mro = NULL;

        PyArg_UnpackTuple(PyList_GET_ITEM(temp, i), <------ HERE
                          "", 2, 3, &cls, &new_mro, &old_mro);
        /* Do not rollback if cls has a newer version of MRO.  */
```

**How can I fix it?** 
Correct reference usage found in `Python/hamt.c` at line `2805`.
https://github.com/siva-msft/cpython/blob/582aaf19e8b94a70c1f96792197770d604ba0fdf/Python/hamt.c#L2805
**Code extract**:

```cpp
    PyObject *key;
    PyObject *def = NULL;

    if (!PyArg_UnpackTuple(args, "get", 1, 2, &key, &def)) { <------ HERE
        return NULL;
    }
```

---
**Instance 2**
File : `Objects/typeobject.c` 
Enclosing Function : `type_set_bases`
Function : `PyArg_UnpackTuple` 
https://github.com/siva-msft/cpython/blob/582aaf19e8b94a70c1f96792197770d604ba0fdf/Objects/typeobject.c#L825
**Issue in**: _new_mro_

**Code extract**:

```cpp
        PyTypeObject *cls;
        PyObject *new_mro, *old_mro = NULL;

        PyArg_UnpackTuple(PyList_GET_ITEM(temp, i), <------ HERE
                          "", 2, 3, &cls, &new_mro, &old_mro);
        /* Do not rollback if cls has a newer version of MRO.  */
```

**How can I fix it?** 
Correct reference usage found in `Python/hamt.c` at line `2805`.
https://github.com/siva-msft/cpython/blob/582aaf19e8b94a70c1f96792197770d604ba0fdf/Python/hamt.c#L2805
**Code extract**:

```cpp
    PyObject *key;
    PyObject *def = NULL;

    if (!PyArg_UnpackTuple(args, "get", 1, 2, &key, &def)) { <------ HERE
        return NULL;
    }
```

**Comment by siva-msft** [comment]
Definitely an error - however, i dont like the representation... maybe we can groupby function/line num?
